service: formplug

plugins:
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs4.3
  stage: ${file(config.json):STAGE}
  region: ${file(config.json):REGION}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:*:*:table/${file(config.json):TABLE_NAME}"
    - Effect: "Allow"
      Action:
        - "ses:*"
      Resource: ${file(config.json):FROM_ARN}

functions:
  receive:
    handler: receive/handler.handle
    events:
      - http:
          path: /{_to}
          method: post
          request:
            parameters:
              paths:
                _to: true
      - http:
          path: /{_to}/{_format}
          method: post
          request:
            parameters:
              paths:
                _to: true
                _format: true

  send:
    handler: send/handler.handle
    events:
      - stream: 
          arn: ${file(config.json):STREAM}
          batchSize: 1

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(config.json):TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE
